# Generated by Django 5.2.1 on 2025-06-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(default='https://dummy.com/placeholder.jpg'),
            preserve_default=False,
        ),
    ]
