from django.urls import path
from .views import (
    RegisterView,
    get_user_info,
    user_bio_view,
    get_user_posts,
    TrendingPostsView,
    PostDetailView,
    CommentListCreateView,
    CommentDetailView,
    like_post,
    follow_user,
    feed_view,
    search,
    verify_email,
    password_reset_request,
    password_reset_confirm,
    update_avatar,
    TagListView,
    PopularTagListView,
    SuggestedUsersView,
    BookmarkListView,
    UserStatsView,
    NotificationListView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('me/', get_user_info, name='get_user_info'),
    path('posts/', TrendingPostsView.as_view(), name='posts'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('posts/<int:post_id>/comments/', CommentListCreateView.as_view(), name='comments'),
    path('comments/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),
    path('posts/<int:post_id>/like/', like_post, name='like-post'),
    path('posts/user/<str:username>/', get_user_posts, name='user-posts'),
    path('follow/<str:username>/', follow_user, name='follow-user'),
    path('feed/', feed_view, name='feed'),
    path('search/', search, name='search'),
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tags/popular/', PopularTagListView.as_view(), name='tag-popular'),
    path('users/suggested/', SuggestedUsersView.as_view(), name='user-suggested'),
    path('bookmarks/', BookmarkListView.as_view(), name='bookmarks'),
    path('profile/stats/', UserStatsView.as_view(), name='user-stats'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('profile/bio/', user_bio_view),
    path('profile/avatar/', update_avatar, name='update_avatar'),
    path('verify-email/', verify_email, name='verify-email'),
    path('password-reset/', password_reset_request, name='password-reset'),
    path('password-reset-confirm/', password_reset_confirm, name='password-reset-confirm'),
]
