from django.urls import path
from .views import (
    RegisterView,
    get_user_info,
    user_bio_view,
    get_user_posts,
    TrendingPostsView,
    TagPostsView,
    ProfessionPostsView,
    FeelingPostsView,
    ProfessionFeelingPostsView,
    PostDetailView,
    CommentListCreateView,
    ReplyListCreateView,
    CommentDetailView,
    like_post,
    like_comment,
    follow_user,
    list_followers,
    list_following,
    feed_view,
    search,
    verify_email,
    password_reset_request,
    password_reset_confirm,
    update_avatar,
    TagListView,
    PopularTagListView,
    SuggestedUsersView,
    BookmarkListView,
    BookmarkDetailView,
    UserStatsView,
    NotificationListView,
    NotificationDetailView,
    NotificationPreferenceView,
    MessageListCreateView,
    mark_all_notifications_read,
    clear_notifications,
    StoryListCreateView,
    StoryDetailView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('me/', get_user_info, name='get_user_info'),
    path('posts/trending/', TrendingPostsView.as_view(), name='posts-trending'),
    path('posts/', TrendingPostsView.as_view(), name='posts'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('posts/<int:post_id>/comments/', CommentListCreateView.as_view(), name='comments'),
    path('comments/<int:comment_id>/replies/', ReplyListCreateView.as_view(), name='comment-replies'),
    path('comments/<int:pk>/', CommentDetailView.as_view(), name='comment-detail'),
    path('posts/<int:post_id>/like/', like_post, name='like-post'),
    path('comments/<int:comment_id>/like/', like_comment, name='like-comment'),
    path('posts/user/<str:username>/', get_user_posts, name='user-posts'),
    path('posts/tag/<str:name>/', TagPostsView.as_view(), name='tag-posts'),
    path('posts/profession/<str:profession>/', ProfessionPostsView.as_view(), name='profession-posts'),
    path('posts/feeling/<str:feeling>/', FeelingPostsView.as_view(), name='feeling-posts'),
    path('posts/profession/<str:profession>/feeling/<str:feeling>/', ProfessionFeelingPostsView.as_view(), name='profession-feeling-posts'),
    path('follow/<str:username>/', follow_user, name='follow-user'),
    path('users/<str:username>/followers/', list_followers, name='user-followers'),
    path('users/<str:username>/following/', list_following, name='user-following'),
    path('feed/', feed_view, name='feed'),
    path('search/', search, name='search'),
    path('tags/', TagListView.as_view(), name='tag-list'),
    path('tags/popular/', PopularTagListView.as_view(), name='tag-popular'),
    path('users/suggested/', SuggestedUsersView.as_view(), name='user-suggested'),
    path('bookmarks/', BookmarkListView.as_view(), name='bookmarks'),
    path('bookmarks/<int:pk>/', BookmarkDetailView.as_view(), name='bookmark-detail'),
    path('stories/', StoryListCreateView.as_view(), name='story-list'),
    path('stories/<int:pk>/', StoryDetailView.as_view(), name='story-detail'),
    path('profile/stats/', UserStatsView.as_view(), name='user-stats'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/mark_all_read/', mark_all_notifications_read, name='notifications-mark-all-read'),
    path('notifications/clear_all/', clear_notifications, name='notifications-clear-all'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification-detail'),
    path('notification-preferences/', NotificationPreferenceView.as_view(), name='notification-preferences'),
    path('messages/<str:username>/', MessageListCreateView.as_view(), name='messages'),
    path('profile/bio/', user_bio_view),
    path('profile/avatar/', update_avatar, name='update_avatar'),
    path('verify-email/', verify_email, name='verify-email'),
    path('password-reset/', password_reset_request, name='password-reset'),
    path('password-reset-confirm/', password_reset_confirm, name='password-reset-confirm'),
]
