// actionTypes.js
export const UPDATE_BIO = "UPDATE_BIO";
export const UPDATE_BIO_SUCCESS = "UPDATE_BIO_SUCCESS";
export const UPDATE_BIO_FAILURE = "UPDATE_BIO_FAILURE";
export const CLEAR_BIO_STATUS = "CLEAR_BIO_STATUS";

export const UPDATE_PROFESSION = "UPDATE_PROFESSION";
export const UPDATE_PROFESSION_SUCCESS = "UPDATE_PROFESSION_SUCCESS";
export const UPDATE_PROFESSION_FAILURE = "UPDATE_PROFESSION_FAILURE";
export const CLEAR_PROFESSION_STATUS = "CLEAR_PROFESSION_STATUS";
