# Generated by Django 5.2.1 on 2025-06-04 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_image_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
    ]
