# Generated by Django 5.2.1 on 2025-07-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment_parent'),
        ('core', '0009_commentlike'),
    ]

    operations = [
    ]
